image: node:12

cache:
  paths:
    - node_modules/
    - .yarn/

stages:
  - test
  - docs

before_script:
  - node -v
  - npm -v
  - yarn -v
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - yarn --pure-lockfile --cache-folder .yarn

build_and_test:
  stage: test
  script:
    - yarn run build
    - yarn run test:lint
    - yarn run doc

# the docs job published the docs to gitlab pages
pages:
  stage: docs
  script:
    - yarn run doc
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - tags
